### ISSUE TITLE
After building the executable program, run the error

### ISSUE THREAD

**Issue by xueyou2000** [plainionist/TauriDotNetBridge#10]
![Image](https://github.com/user-attachments/assets/08d98b5b-e158-43cb-b8bd-80a6dee8da5f)

- `pnpm tauri dev`  Works fine
- `pnpm tauri build` Generate tauri-dotnet-sample.app and tauri-dotnet-sample_0.1.0_aarch64.dmg

My Device use iMac Apple M3
open `tauri-dotnet-sample.app` get error:

```txt
{"app_name":"tauri-dotnet-sample","timestamp":"2025-01-27 12:56:38.00 +0800","app_version":"0.1.0","slice_uuid":"f0a0f5e5-803d-3edc-a7b6-cfda60bfbe4a","build_version":"20250127.044959","platform":1,"bundleID":"com.tauri-dotnet-sample.app","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 14.7 (23H124)","roots_installed":0,"name":"tauri-dotnet-sample","incident_id":"4ADA66C7-C26E-4225-8637-A7C14AF4DCF0"}
{
  "uptime" : 470000,
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "Mac15,5",
  "coalitionID" : 163910,
  "osVersion" : {
    "train" : "macOS 14.7",
    "build" : "23H124",
    "releaseType" : "User"
  },
  "captureTime" : "2025-01-27 12:56:38.1790 +0800",
  "codeSigningMonitor" : 1,
  "incident" : "4ADA66C7-C26E-4225-8637-A7C14AF4DCF0",
  "pid" : 82959,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2025-01-27 12:56:37.9610 +0800",
  "procStartAbsTime" : 11454223203592,
  "procExitAbsTime" : 11454228393932,
  "procName" : "tauri-dotnet-sample",
  "procPath" : "\/Users\/USER\/Downloads\/*\/tauri-dotnet-sample.app\/Contents\/MacOS\/tauri-dotnet-sample",
  "bundleInfo" : {"CFBundleShortVersionString":"0.1.0","CFBundleVersion":"20250127.044959","CFBundleIdentifier":"com.tauri-dotnet-sample.app"},
  "storeInfo" : {"deviceIdentifierForVendor":"8F1C2141-FD0C-5900-9569-E2E4CA167B1E","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.tauri-dotnet-sample.app",
  "crashReporterKey" : "D869C849-F3AF-B3D9-5771-028F925F7FD5",
  "codeSigningID" : "tauri_dotnet_sample-f16eb0cb1fc01d3c",
  "codeSigningTeamID" : "",
  "codeSigningFlags" : 570556929,
  "codeSigningValidationCategory" : 10,
  "codeSigningTrustLevel" : 4294967295,
  "instructionByteStream" : {"beforePC":"fyMD1f17v6n9AwCRd+D\/l78DAJH9e8Go\/w9f1sADX9YQKYDSARAA1A==","atPC":"AwEAVH8jA9X9e7+p\/QMAkWzg\/5e\/AwCR\/XvBqP8PX9bAA1\/WcAqA0g=="},
  "wakeTime" : 4131,
  "sleepWakeUUID" : "B28B4967-7AC0-4BC4-8220-CBA81E6FC438",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"flags":0,"code":6,"namespace":"SIGNAL","indicator":"Abort trap: 6","byProc":"tauri-dotnet-sample","byPid":82959},
  "asi" : {"libsystem_c.dylib":["abort() called"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"threadState":{"x":[{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":6125961520},{"value":5},{"value":96},{"value":627396607158950611},{"value":627396599765144979},{"value":17},{"value":2},{"value":15},{"value":131072},{"value":0},{"value":0},{"value":328},{"value":8642668320},{"value":0},{"value":6},{"value":8467550016,"symbolLocation":0,"symbol":"_main_thread"},{"value":259},{"value":8467550240,"symbolLocation":224,"symbol":"_main_thread"},{"value":4349112320,"symbolLocation":6784,"symbol":"crossbeam_utils::atomic::atomic_cell::lock::LOCKS::h0dfa69b30fce0297"},{"value":0},{"value":267264},{"value":0},{"value":68719476751},{"value":6125972456}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6724459552},"cpsr":{"value":1073745920},"fp":{"value":6125971488},"sp":{"value":6125971456},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6724228560,"matchesCrashFrame":1},"far":{"value":0}},"id":8544178,"triggered":true,"name":"main","queue":"com.apple.main-thread","frames":[{"imageOffset":38352,"symbol":"__pthread_kill","symbolLocation":8,"imageIndex":5},{"imageOffset":27680,"symbol":"pthread_kill","symbolLocation":288,"imageIndex":6},{"imageOffset":485936,"symbol":"abort","symbolLocation":180,"imageIndex":7},{"imageOffset":5108232,"symbol":"std::sys::pal::unix::abort_internal::h4b0b63493bdd72f5","symbolLocation":12,"imageIndex":4},{"imageOffset":5092096,"symbol":"std::panicking::rust_panic_with_hook::h533a16f5f89e4278","symbolLocation":876,"imageIndex":4},{"imageOffset":5090952,"symbol":"std::panicking::begin_panic_handler::_$u7b$$u7b$closure$u7d$$u7d$::h168c3a4362c8e4df","symbolLocation":104,"imageIndex":4},{"imageOffset":5087076,"symbol":"std::sys::backtrace::__rust_end_short_backtrace::h601e3529ca2053df","symbolLocation":12,"imageIndex":4},{"imageOffset":5090152,"symbol":"rust_begin_unwind","symbolLocation":32,"imageIndex":4},{"imageOffset":5331988,"symbol":"core::panicking::panic_nounwind_fmt::h6251928767c378a3","symbolLocation":52,"imageIndex":4},{"imageOffset":5332108,"symbol":"core::panicking::panic_nounwind::he5e0e92598e09d63","symbolLocation":60,"imageIndex":4},{"imageOffset":5332344,"symbol":"core::panicking::panic_cannot_unwind::hc39e9acf1ae7ca4b","symbolLocation":24,"imageIndex":4},{"imageOffset":3487924,"symbol":"tao::platform_impl::platform::app_delegate::did_finish_launching::h99bc735fb9a78e2f","symbolLocation":248,"imageIndex":4},{"imageOffset":471364,"symbol":"__CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__","symbolLocation":148,"imageIndex":8},{"imageOffset":1078232,"symbol":"___CFXRegistrationPost_block_invoke","symbolLocation":88,"imageIndex":8},{"imageOffset":1078048,"symbol":"_CFXRegistrationPost","symbolLocation":440,"imageIndex":8},{"imageOffset":267896,"symbol":"_CFXNotificationPost","symbolLocation":768,"imageIndex":8},{"imageOffset":37572,"symbol":"-[NSNotificationCenter postNotificationName:object:userInfo:]","symbolLocation":88,"imageIndex":9},{"imageOffset":271216,"symbol":"-[NSApplication _postDidFinishNotification]","symbolLocation":284,"imageIndex":10},{"imageOffset":270624,"symbol":"-[NSApplication _sendFinishLaunchingNotification]","symbolLocation":172,"imageIndex":10},{"imageOffset":263796,"symbol":"-[NSApplication(NSAppleEventHandling) _handleAEOpenEvent:]","symbolLocation":504,"imageIndex":10},{"imageOffset":262768,"symbol":"-[NSApplication(NSAppleEventHandling) _handleCoreEvent:withReplyEvent:]","symbolLocation":492,"imageIndex":10},{"imageOffset":205140,"symbol":"-[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:]","symbolLocation":316,"imageIndex":9},{"imageOffset":204616,"symbol":"_NSAppleEventManagerGenericHandler","symbolLocation":80,"imageIndex":9},{"imageOffset":47556,"imageIndex":11},{"imageOffset":45804,"imageIndex":11},{"imageOffset":18600,"symbol":"aeProcessAppleEvent","symbolLocation":488,"imageIndex":11},{"imageOffset":274476,"symbol":"AEProcessAppleEvent","symbolLocation":68,"imageIndex":12},{"imageOffset":237524,"symbol":"_DPSNextEvent","symbolLocation":1440,"imageIndex":10},{"imageOffset":8586448,"symbol":"-[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]","symbolLocation":700,"imageIndex":10},{"imageOffset":184316,"symbol":"-[NSApplication run]","symbolLocation":476,"imageIndex":10},{"imageOffset":2252872,"symbol":"tao::platform_impl::platform::event_loop::EventLoop$LT$T$GT$::run::h7f08d6944001c2ad","symbolLocation":704,"imageIndex":4},{"imageOffset":2343164,"symbol":"_$LT$tauri_runtime_wry..Wry$LT$T$GT$$u20$as$u20$tauri_runtime..Runtime$LT$T$GT$$GT$::run::h156632fe47c5c073","symbolLocation":348,"imageIndex":4},{"imageOffset":1155128,"symbol":"tauri::app::Builder$LT$R$GT$::run::h4d0cb5cd8eae032a","symbolLocation":4568,"imageIndex":4},{"imageOffset":2472816,"symbol":"tauri_dotnet_sample_lib::run::hfa449fa20582d6bb","symbolLocation":1036,"imageIndex":4},{"imageOffset":19152,"symbol":"std::sys::backtrace::__rust_begin_short_backtrace::h850bc066fbf8a68e","symbolLocation":12,"imageIndex":4},{"imageOffset":19128,"symbol":"std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::hb78a313751c8d702","symbolLocation":16,"imageIndex":4},{"imageOffset":5055948,"symbol":"std::rt::lang_start_internal::hacda2dedffd2edb4","symbolLocation":1092,"imageIndex":4},{"imageOffset":19244,"symbol":"main","symbolLocation":52,"imageIndex":4},{"imageOffset":24916,"symbol":"start","symbolLocation":2476,"imageIndex":13}]},{"id":8544192,"frames":[{"imageOffset":7456,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":6}],"threadState":{"x":[{"value":6126563328},{"value":10499},{"value":6126026752},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6126563328},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6724439328},"far":{"value":0}}},{"id":8544193,"threadState":{"x":[{"value":18446744073709551612},{"value":0},{"value":4294967295},{"value":0},{"value":8467565248,"symbolLocation":0,"symbol":"_dispatch_main_q"},{"value":2},{"value":6127134328},{"value":9},{"value":0},{"value":105553119075520},{"value":4},{"value":16383},{"value":68719476736},{"value":9005068950962176},{"value":2043},{"value":3846334607},{"value":515},{"value":8550556400},{"value":0},{"value":4294967295},{"value":0},{"value":6127134592},{"value":16777217},{"value":6127136992},{"value":105553176992360},{"value":0},{"value":0},{"value":105553119076096},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6722690520},"cpsr":{"value":1073745920},"fp":{"value":6127134400},"sp":{"value":6127134368},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6724201356},"far":{"value":0}},"queue":"com.apple.WebKit.ServicesController","frames":[{"imageOffset":11148,"symbol":"__ulock_wait","symbolLocation":8,"imageIndex":5},{"imageOffset":19928,"symbol":"_dlock_wait","symbolLocation":56,"imageIndex":15},{"imageOffset":19340,"symbol":"_dispatch_thread_event_wait_slow","symbolLocation":56,"imageIndex":15},{"imageOffset":80836,"symbol":"__DISPATCH_WAIT_FOR_QUEUE__","symbolLocation":368,"imageIndex":15},{"imageOffset":79728,"symbol":"_dispatch_sync_f_slow","symbolLocation":148,"imageIndex":15},{"imageOffset":6894444,"symbol":"void std::__1::__call_once_proxy[abi:sn170006]<std::__1::tuple<WebKit::ServicesController::refreshExistingServices(bool)::'block-literal'::$_8&&>>(void*)","symbolLocation":112,"imageIndex":16},{"imageOffset":93764,"symbol":"std::__1::__call_once(unsigned long volatile&, void*, void (*)(void*))","symbolLocation":180,"imageIndex":17},{"imageOffset":6872112,"symbol":"invocation function for block in WebKit::ServicesController::refreshExistingServices(bool)","symbolLocation":360,"imageIndex":16},{"imageOffset":10064,"symbol":"_dispatch_call_block_and_release","symbolLocation":32,"imageIndex":15},{"imageOffset":17384,"symbol":"_dispatch_client_callout","symbolLocation":20,"imageIndex":15},{"imageOffset":47636,"symbol":"_dispatch_lane_serial_drain","symbolLocation":748,"imageIndex":15},{"imageOffset":50500,"symbol":"_dispatch_lane_invoke","symbolLocation":380,"imageIndex":15},{"imageOffset":94928,"symbol":"_dispatch_root_queue_drain_deferred_wlh","symbolLocation":288,"imageIndex":15},{"imageOffset":92996,"symbol":"_dispatch_workloop_worker_thread","symbolLocation":404,"imageIndex":15},{"imageOffset":12300,"symbol":"_pthread_wqthread","symbolLocation":288,"imageIndex":6},{"imageOffset":7464,"symbol":"start_wqthread","symbolLocation":8,"imageIndex":6}]},{"id":8544196,"frames":[{"imageOffset":7456,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":6}],"threadState":{"x":[{"value":6127710208},{"value":20483},{"value":6127173632},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6127710208},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6724439328},"far":{"value":0}}},{"id":8544201,"name":"JavaScriptCore libpas scavenger","threadState":{"x":[{"value":260},{"value":0},{"value":0},{"value":0},{"value":0},{"value":160},{"value":0},{"value":99998952},{"value":6128283288},{"value":0},{"value":4542277656},{"value":2},{"value":0},{"value":0},{"value":0},{"value":0},{"value":305},{"value":8642668248},{"value":0},{"value":4542277632},{"value":4542277696},{"value":6128283872},{"value":99998952},{"value":0},{"value":0},{"value":1},{"value":256},{"value":8451543040,"symbolLocation":16,"symbol":"pas_large_sharing_tree_jettisoned_nodes"},{"value":8451543040,"symbolLocation":16,"symbol":"pas_large_sharing_tree_jettisoned_nodes"}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6724461916},"cpsr":{"value":1610616832},"fp":{"value":6128283408},"sp":{"value":6128283264},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6724208076},"far":{"value":0}},"frames":[{"imageOffset":17868,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":5},{"imageOffset":30044,"symbol":"_pthread_cond_wait","symbolLocation":1228,"imageIndex":6},{"imageOffset":22387620,"symbol":"scavenger_thread_main","symbolLocation":1316,"imageIndex":18},{"imageOffset":28564,"symbol":"_pthread_start","symbolLocation":136,"imageIndex":6},{"imageOffset":7476,"symbol":"thread_start","symbolLocation":8,"imageIndex":6}]},{"id":8544203,"name":"com.apple.coreanimation.render-server","threadState":{"x":[{"value":268451845},{"value":21525170190},{"value":8589934592},{"value":0},{"value":0},{"value":204522047668224},{"value":2},{"value":0},{"value":18446744073709550527},{"value":0},{"value":0},{"value":1},{"value":47619},{"value":2095104},{"value":2043},{"value":3015706751},{"value":18446744073709551569},{"value":3017801744},{"value":0},{"value":0},{"value":2},{"value":204522047668224},{"value":0},{"value":0},{"value":6129363640},{"value":8589934592},{"value":21525170190},{"value":21525170190},{"value":4345301006,"symbolLocation":1210,"symbol":"aho_corasick::nfa::noncontiguous::Compiler::fill_failure_transitions::hedea7560fc8bafad"}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6724269508},"cpsr":{"value":4096},"fp":{"value":6129363488},"sp":{"value":6129363408},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6724193748},"far":{"value":0}},"frames":[{"imageOffset":3540,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":5},{"imageOffset":79300,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":5},{"imageOffset":39332,"symbol":"mach_msg_overwrite","symbolLocation":476,"imageIndex":5},{"imageOffset":4440,"symbol":"mach_msg","symbolLocation":24,"imageIndex":5},{"imageOffset":293744,"symbol":"CA::Render::Server::server_thread(void*)","symbolLocation":580,"imageIndex":19},{"imageOffset":293148,"symbol":"thread_fun(void*)","symbolLocation":32,"imageIndex":19},{"imageOffset":28564,"symbol":"_pthread_start","symbolLocation":136,"imageIndex":6},{"imageOffset":7476,"symbol":"thread_start","symbolLocation":8,"imageIndex":6}]},{"id":8544206,"frames":[{"imageOffset":7456,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":6}],"threadState":{"x":[{"value":6129954816},{"value":47111},{"value":6129418240},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6129954816},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6724439328},"far":{"value":0}}},{"id":8544211,"frames":[{"imageOffset":7456,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":6}],"threadState":{"x":[{"value":6130528256},{"value":48643},{"value":6129991680},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6130528256},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6724439328},"far":{"value":0}}},{"id":8544212,"name":"WebCore: Scrolling","threadState":{"x":[{"value":268451845},{"value":21592279046},{"value":8589934592},{"value":259497629057024},{"value":0},{"value":259497629057024},{"value":2},{"value":4294967295},{"value":18446744073709550527},{"value":60419},{"value":0},{"value":1},{"value":60419},{"value":38519},{"value":0},{"value":0},{"value":18446744073709551569},{"value":8642652448},{"value":0},{"value":4294967295},{"value":2},{"value":259497629057024},{"value":0},{"value":259497629057024},{"value":6131097560},{"value":8589934592},{"value":21592279046},{"value":21592279046},{"value":4412409862}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6724269508},"cpsr":{"value":4096},"fp":{"value":6131097408},"sp":{"value":6131097328},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6724193748},"far":{"value":0}},"frames":[{"imageOffset":3540,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":5},{"imageOffset":79300,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":5},{"imageOffset":39332,"symbol":"mach_msg_overwrite","symbolLocation":476,"imageIndex":5},{"imageOffset":4440,"symbol":"mach_msg","symbolLocation":24,"imageIndex":5},{"imageOffset":517760,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":8},{"imageOffset":511812,"symbol":"__CFRunLoopRun","symbolLocation":1208,"imageIndex":8},{"imageOffset":508980,"symbol":"CFRunLoopRunSpecific","symbolLocation":608,"imageIndex":8},{"imageOffset":1025116,"symbol":"CFRunLoopRun","symbolLocation":64,"imageIndex":8},{"imageOffset":1714464,"symbol":"WTF::Detail::CallableWrapper<WTF::RunLoop::create(char const*, WTF::ThreadType, WTF::Thread::QOS)::$_1, void>::call()","symbolLocation":52,"imageIndex":18},{"imageOffset":1858988,"symbol":"WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*)","symbolLocation":244,"imageIndex":18},{"imageOffset":33632,"symbol":"WTF::wtfThreadEntryPoint(void*)","symbolLocation":16,"imageIndex":18},{"imageOffset":28564,"symbol":"_pthread_start","symbolLocation":136,"imageIndex":6},{"imageOffset":7476,"symbol":"thread_start","symbolLocation":8,"imageIndex":6}]},{"id":8544213,"name":"CVDisplayLink","threadState":{"x":[{"value":260},{"value":0},{"value":0},{"value":0},{"value":0},{"value":65704},{"value":0},{"value":16294834},{"value":1},{"value":0},{"value":5579139664},{"value":2},{"value":0},{"value":0},{"value":0},{"value":0},{"value":305},{"value":8642668248},{"value":0},{"value":5579139640},{"value":5579139704},{"value":1},{"value":16294834},{"value":0},{"value":0},{"value":1},{"value":256},{"value":8449118880,"symbolLocation":0,"symbol":"CVHostTimeBase::sToNanosDenominator"},{"value":8449120776,"symbolLocation":0,"symbol":"kZeroVideoTime"}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6724461960},"cpsr":{"value":2684358656},"fp":{"value":6131674544},"sp":{"value":6131674400},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6724208076},"far":{"value":0}},"frames":[{"imageOffset":17868,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":5},{"imageOffset":30088,"symbol":"_pthread_cond_wait","symbolLocation":1272,"imageIndex":6},{"imageOffset":16100,"symbol":"CVDisplayLink::waitUntil(unsigned long long)","symbolLocation":328,"imageIndex":20},{"imageOffset":12208,"symbol":"CVDisplayLink::runIOThread()","symbolLocation":504,"imageIndex":20},{"imageOffset":28564,"symbol":"_pthread_start","symbolLocation":136,"imageIndex":6},{"imageOffset":7476,"symbol":"thread_start","symbolLocation":8,"imageIndex":6}]},{"id":8544215,"name":"CVDisplayLink","threadState":{"x":[{"value":260},{"value":0},{"value":0},{"value":0},{"value":0},{"value":65704},{"value":0},{"value":13712334},{"value":1},{"value":0},{"value":5561944656},{"value":2},{"value":0},{"value":0},{"value":0},{"value":0},{"value":305},{"value":8642668248},{"value":0},{"value":5561944632},{"value":5561944696},{"value":1},{"value":13712334},{"value":0},{"value":0},{"value":1},{"value":256},{"value":8449118880,"symbolLocation":0,"symbol":"CVHostTimeBase::sToNanosDenominator"},{"value":8449120776,"symbolLocation":0,"symbol":"kZeroVideoTime"}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6724461960},"cpsr":{"value":2684358656},"fp":{"value":6132247984},"sp":{"value":6132247840},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6724208076},"far":{"value":0}},"frames":[{"imageOffset":17868,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":5},{"imageOffset":30088,"symbol":"_pthread_cond_wait","symbolLocation":1272,"imageIndex":6},{"imageOffset":16100,"symbol":"CVDisplayLink::waitUntil(unsigned long long)","symbolLocation":328,"imageIndex":20},{"imageOffset":12208,"symbol":"CVDisplayLink::runIOThread()","symbolLocation":504,"imageIndex":20},{"imageOffset":28564,"symbol":"_pthread_start","symbolLocation":136,"imageIndex":6},
```

**Comment by xueyou2000** [comment]
Additional information: 
  When I run `pnpm tauri build --no-bundle`, directly executing `/src-tauri/target/release/app` works fine

**Comment by plainionist** [comment]
Pls have a look at this issue: https://github.com/plainionist/TauriDotNetBridge/issues/8
i just updated the readme and the tauri.conf.json of the sample app
can u pls check whether this solves your problem?

**Comment by xueyou2000** [comment]
> Pls have a look at this issue: [#8](https://github.com/plainionist/TauriDotNetBridge/issues/8) i just updated the readme and the tauri.conf.json of the sample app can u pls check whether this solves your problem?

Still not working properly, in macos the bundle target is  "xx.app"

![Image](https://github.com/user-attachments/assets/deb1593b-1775-496e-bfad-36b8e1f202c2)

The content structure is as follows:

![Image](https://github.com/user-attachments/assets/0e485af5-872a-49d2-8bb0-c97388a2a123)

I guess the reason is in the processing path logic of the "tauri-dotnet-bridge-host" code. It is necessary to correctly find the resources path of different platforms. Is there an API for tauri to get resources?

```rust
let exe_path = env::current_exe().expect("Failed to get the executable path");
let dotnet_dir = exe_path.parent().expect("Failed to get the executable directory").join("dotnet");
```
